### PR TITLE
Set Min Pane Size to Current Issue #6

### PR DESCRIPTION
**Pull request by Monkeymerlot**
I forgot to create a pull request back to main the other day. See issue #6 for details

### CODE REVIEW

**Comment by HopeHarrison** [comment]
After trying this out for a bit, I found it usually works but there is sometimes a strange behavior.

On the test VI if I select the leftmost top pane, and click "Set To Current", the pane gets a little bit bigger, and it will keep getting bigger every time I click "Set To Current".

Are you able to see the same behavior? I can't figure out why it's happening or the exact circumstances to recreate it. I'll keep thinking about it, see if I can come up with anything.

**Comment by Monkeymerlot** [comment]
I just checked and can confirm the behavior. It happens on other panels as well. I noticed that it stops when I change the splitter bar beneath it from "Sticks Bottom" to "Sticks Top" or "Proportional".

**Comment by Monkeymerlot** [comment]
It seems that LabVIEW also has the same behavior when you right click the splitter select properties for the above panel:
image
Initial View:
image
After clicking "Set to current pane size":
image
And clicking it again:
image
and every time I click it after that it just increases by 5. 

I did some testing and the only thing that seems to be rather consistent is that it will work fine no matter what if the front panel is closed. 
Some further testing showed that if I put down fresh splitters on a front panel, everything worked perfectly even with the other settings the same as the cases you found that were problematic, that was until I resized them. Then it started producing the weird behavior.

**Comment by HopeHarrison** [comment]
Wow, you are right, the same thing happens from the LabVIEW UI! If that's the case I think I'll go ahead and merge this as is - can't be expected to be better than LabVIEW itself, right?

PS: Sorry for the delay, it's sometimes hard to find the time for side projects, even though I love working on them once I do!

**Comment by Monkeymerlot** [comment]
Sweet! And no worries!

**Pull request merged**
