### PR TITLE
Feature Addition: Splitter Style

### PR DESCRIPTION
**Pull request by ItsMeAshiq**
Added new drop down menu to select Splitter Style
image

Also provided a **Refresh** button to update the current Style if the user modifies the style directly in the VI while keeping the tool open.
image

Here's a preview 
Pane Relief - Splitter Style

### CODE REVIEW

**Comment by ItsMeAshiq** [comment]
The committed code is developed using LabVIEW 2020.

**Comment by HopeHarrison** [comment]
Hi, thank you for your work on this. I'm not able to respond to pull requests super quickly, but I always appreciate them and will respond eventually.

I had to change your implementation a little bit. You were caching the XML text in a feedback node, but that doesn't really work since multiple class instances might use that VI. If you want to do caching like that, you could store the cache in the class private data. But I don't think it's necessary - for me I got just fine performance reading it every time.

I also moved your refresh button so it refreshes the whole thing, in case the user makes changes manually on the front panel while the QD shortcut is open.

You also asked why the special library handling is needed here:
image
You will find the reasons for this in Issue #1, basically to fix an issue where VIs would lose their class membership. I have added a comment to the code explaining it.

**Comment by ItsMeAshiq** [comment]
Hi, thanks for the update.

And one more thing I have missed to take into account of - NXG style FP elements were introduced only from LV 2018.

So, we might need to add the following code snippet to handle the NXG option in the **Splitter: Style** list,

Splitter: Style Disable NXG splitter style for LV versions upto 2017

**Comment by HopeHarrison** [comment]
Good idea. I just added this.

**Pull request merged**
